### PR TITLE
Port to v7.11.0

### PR DESCRIPTION
**Pull request by iggysha**
This PR is a port to v7.11.0

Configuration files are perfectly aligned with v7.11.0 making comparison easier.

There is new music demo application.

Keyboard/encoder demo is now fully supported with keyboard and mouse wheel drivers.

Segmentation faults are resolved (local variables in hal_init() are now static).

### CODE REVIEW

**Comment by microwavesafe** [comment]
If I merge your V8 pull request do we need this one as well? I'm tempted just to merge the V8 pull request, what do you think?

**Comment by iggysha** [comment]
I guess I would merge v7.11.0 and tag it, then merge v8.0.0 and tag it as well.

**Comment by microwavesafe** [comment]
Sounds like a good idea. I realise that you have update lv_conf.h to directly match the release, but this means that a lot of changes are to add some spaces, not really code changes. Do we need these or can we get away with removing the formatting only changes?

**Comment by iggysha** [comment]
If it was only formatting then it would lead someone into thinking that code changed, so commit wouldn't make much sense. Nevertheless, code did change, so it was an opportunity to align formatting as well, to make comparison to template easier. That being said, I don't have preferences so it's really up to you; if you want to remove formatting changes so that code changes are easier to track then feel free to do so. I can do it as well, just let me know if this is the way you wanna go...

**Pull request merged**
